# Dockerfile.server
FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install --include=optional

# Copy app source code
COPY . .

# Expose port
EXPOSE 5005

# Start server
CMD ["node", "app.js"]
